site_name: Took For You
site_author: Alex Macedo.
site_url: https://Alexxmfs.github.io/mkdocs-lamp-voice/
  
theme:
  name: material
  favicon: images/favicon.png
  language: en
  icon: 
    logo: fontawesome/solid/hat-cowboy
  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tracking
  
  palette:

  # Palette toggle for dark mode
  - scheme: slate
    primary: black
    accent: green
    toggle: 
      icon: material/weather-night
      name: Switch to light mode

  # Pallete toggle for ligth mode
  - scheme: default
    primary: blue
    accent: green
    toggle: 
      icon: material/weather-sunny
      name: Switch to dark mode


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - markdown_grid_tables:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - tables
  

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:
  - Home: index.md
  - Começar:
    - 2024.1: ./Começar/2024.1.md
  - Diagrama:
    - Microservices:
      - Diagrama: ./diagrama/microservices/diagrama.md
      - Jogadores: ./diagrama/microservices/jogadores.md
      - Auth: ./diagrama/microservices/auth.md
      - Discovery: ./diagrama/microservices/discovery.md
      - Gateway: ./diagrama/microservices/gateway.md
    - DevOps:
      - Observability: ./handout/devops/observability.md
    #   - Roadmap: ./handout/devops-roadmap.md
    #   - Jenkins: ./handout/devops-jenkins.md
    #   - Docker: ./handout/devops-docker.md
    #   - Kubernetes: ./handout/devops-kubernetes.md
  - Docker:
    - Spring Boot Cloud: ./Docker/spring-boot-cloud.md
    - Testing: ./Docker/testing.md
    - Documentation: ./Docker/documentation.md
    - Concepts: ./platform/concepts.md
    - Microservices: ./platform/microservices.md
    - Discovery: ./platform/discovery.md
    - Gateway: ./platform/gateway.md
    - Config: ./platform/config.md
    - Load Balancing: ./platform/load-balancing.md
    - Circuit Breaker: ./platform/circuit-breaker.md
    - Security:
      - Concepts: ./platform/security/concepts.md
      - JWT: ./platform/security/jwt.md
      - OAuth2: ./platform/security/oauth2.md
      # - Auth Service: ./platform/security/auth-service.md
      # - OpenID: openid.md
      # - SSO: sso.md
    - Communication: ./platform/communcation.md
    - Observability:
      - Monitoring: ./platform/observability/monitoring.md
      - Logging: ./platform/observability/logging.md
      - Tracing: ./platform/observability/tracing.md
    - Messaging: 
      - Concepts: ./platform/messaging/concepts.md
      - Kafka: ./platform/messaging/kafka.md
      - RabbitMQ: ./platform/messaging/rabbitmq.md
    - Database:
      - Flyway: ./platform/database/flyway.md
      - Caching: ./platform/database/caching.md
      # - MongoDB: mongodb.md
      # - Elasticsearch: elasticsearch.md
    - Payment: ./platform/payment.md
    - Concepts: ./devops/concepts.md
    - Version Control: ./devops/version-control-system.md
    - Docker: ./devops/docker.md
    - Packaging: ./devops/packaging.md
    - Release: ./devops/release.md
    # - Nexus: nexus.md
    # - SonarQube: sonarqube.md
    - Kubernetes: ./devops/kubernetes.md
    - AWS: ./cloud/aws.md
    - GCP: ./cloud/gcp.md
    - Azure: ./cloud/azure.md
    - GitActions: ./cloud/gitactions.md
    - Terraform: ./cloud/terraform.md
    - Concepts: ./business/concepts.md
    - REST vs GraphQL: ./appendix/rest-vs-graphql.md
    - Versioning REST APIs: ./appendix/versioning-rest-apis.md
    - TLS for microservices: ./appendix/tls-for-microservices.md
  - Disclaimer: ./disclaimer.md

# teste
# python -m venv venv
# Set-ExecutionPolicy -ExecutionPolicy  RemoteSigned -Scope Process
# venv\Scripts\Activate.ps1
# pip install mkdocs-material
# pip install markdown_grid_tables
# mkdocs serve
# mkdocs gh-deploy